package model.paint.strategy;

import java.awt.geom.AffineTransform;

import model.paint.ShapePaintStrategy;
import model.paint.shape.Fish1PolygonFactory;

/**
 * @author zihanli
 *Paint strategy that paints a fish-shaped Polygon generated by a Fish1PolyfonFactory
 */
public class Fish1PaintStrategy extends ShapePaintStrategy {

	/**
	 * No-parameter constructor that instantiates the AffineTransform for internal use.
	 */
	public Fish1PaintStrategy() {
		super(new AffineTransform(), new Fish1PolygonFactory().makeShape(0, 0, 1, 1));
		// TODO Auto-generated constructor stub
	}

}
